name: Lint GitHub Actions workflows
on:
  push:
    branches: ["main"]
    paths: [".github/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/**"]
  merge_group:

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    uses: Not-Nik/neqo/.github/workflows/actionlint.yml@external-workflow-calling
