name: Clippy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clippy:
    name: clippy
    uses: Not-Nik/neqo/.github/workflows/clippy.yml@external-workflow-calling
