name: Deny
on:
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  deny:
    name: deny
    uses: Not-Nik/neqo/.github/workflows/deny.yml@external-workflow-calling
