name: Dependency Review
on:
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    name: dependency-review
    uses: Not-Nik/neqo/.github/workflows/dependency-review.yml@external-workflow-calling
