name: Machete
on:
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  machete:
    name: machete
    uses: Not-Nik/neqo/.github/workflows/machete.yml@external-workflow-calling
