name: Find mutants
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mutants:
    name: mutants
    uses: Not-Nik/neqo/.github/workflows/mutants.yml@external-workflow-calling
