name: Format
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rustfmt:
    name: rustfmt
    uses: Not-Nik/neqo/.github/workflows/rustfmt.yml@external-workflow-calling
