name: Sanitize
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sanitize:
    name: Sanitize
    uses: Not-Nik/neqo/.github/workflows/sanitize.yml@external-workflow-calling
