name: Check semver
on:
  pull_request:
    branches: ["main"]
  merge_group:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  semver:
    name: semver
    uses: Not-Nik/neqo/.github/workflows/semver.yml@external-workflow-calling
