name: Check semver
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semver:
    name: Check semver
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: mozilla/actions/rust@25cb84d060946c0ad6d2c3f79da479b16d180d71 # v1.1.0
        with:
          tools: cargo-semver-checks
          token: ${{ github.token }}

      - uses: mozilla/actions/nss@25cb84d060946c0ad6d2c3f79da479b16d180d71 # v1.1.0
        with:
          version-file: min_version.txt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check semver
        run: |
          LATEST_TAG_COMMIT=$(git rev-list --tags --max-count=1)
          # shellcheck disable=SC2086
          cargo semver-checks --default-features --baseline-rev "$LATEST_TAG_COMMIT"
